# Generated by Django 4.2.5 on 2024-01-03 18:08

from django.db import migrations, models
import django.db.models.deletion
import restAPI.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('U_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('userType', models.CharField(choices=[(restAPI.models.UserType['ADMIN'], 'admin'), (restAPI.models.UserType['EXPERT'], 'expert'), (restAPI.models.UserType['PARENT'], 'parent'), (restAPI.models.UserType['SPECIAL_PERSON'], 'special_person')], default='admin', max_length=20)),
                ('fullName', models.CharField(max_length=255, null=True)),
                ('userName', models.CharField(max_length=255, null=True, unique=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('address', models.TextField(max_length=500, null=True)),
                ('mobileNo', models.CharField(max_length=10, null=True)),
                ('country', models.CharField(max_length=255, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('OTP_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('otp', models.CharField(max_length=6)),
                ('email', models.CharField(max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('token_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Special_Person',
            fields=[
                ('sp_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('disability_type', models.CharField(max_length=255)),
                ('disability_cert', models.ImageField(upload_to='media/')),
                ('education', models.CharField(max_length=255)),
                ('hobbies', models.CharField(max_length=255)),
                ('U_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restAPI.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('Q_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('dislike_count', models.PositiveIntegerField(default=0)),
                ('U_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restAPI.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='expert',
            fields=[
                ('expert_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=255)),
                ('proof_of_designation', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('U_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restAPI.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('A_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Answer', models.CharField()),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('dislike_count', models.PositiveIntegerField(default=0)),
                ('Q_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restAPI.question')),
                ('U_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restAPI.customuser')),
            ],
        ),
    ]
