# Generated by Django 4.2.5 on 2024-01-02 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0002_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='Q_id',
        ),
    ]
