# Generated by Django 4.2.5 on 2023-12-29 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0002_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
