# Generated by Django 4.2.5 on 2024-01-03 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0005_remove_question_categories_alter_customuser_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
